// REDUCER TYPES
//// USER
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';

//// UI
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

//// DATA
export const LOADING_DATA = 'LOADING_DATA';
export const SET_SQUEAKS_LIST = 'SET_SQUEAKS_LIST';
export const SET_SQUEAK = 'SET_SQUEAK'
export const POST_SQUEAK = 'POST_SQUEAK';
export const LIKE_SQUEAK = 'LIKE_SQUEAK';
export const UNLIKE_SQUEAK = 'UNLIKE_SQUEAK';
export const DELETE_SQUEAK = 'DELETE_SQUEAK';
